### YamlMime:Landing
title: Ansible na documentação do Azure
summary: Saiba como usar o Ansible para automatizar o provisionamento de nuvem, gerenciamento de configuração e implantações de aplicativo.
metadata:
  title: Ansible na documentação do Azure
  description: Saiba como usar o Ansible para automatizar o provisionamento de nuvem, gerenciamento de configuração e implantações de aplicativo.
  services: azure
  ms.service: ansible
  ms.topic: landing-page
  author: TomArcherMsft
  ms.author: tarcher
  ms.date: 09/11/2019
  ms.openlocfilehash: 042a58a2ba6900f0a97698e9fe37fdfb22552578
  ms.sourcegitcommit: aef6040b1321881a7eb21348b4fd5cd6a5a1e8d8
  ms.translationtype: HT
  ms.contentlocale: pt-BR
  ms.lasthandoff: 10/09/2019
  ms.locfileid: "72169723"
landingContent:
- title: Sobre o Ansible no Azure
  linkLists:
  - linkListType: overview
    links:
    - text: Sobre o Ansible no Azure
      url: ansible-overview.md
  - linkListType: reference
    links:
    - text: Versões e recursos
      url: ./ansible-matrix.md
    - text: Todos os módulos do Azure
      url: https://docs.ansible.com/ansible/latest/modules/list_of_cloud_modules#azure
- title: Instalar e configurar o Ansible
  linkLists:
  - linkListType: quickstart
    links:
    - text: Implantar o modelo de solução do Ansible para o CentOS
      url: ansible-deploy-solution-template.md
    - text: Instalar o Ansible em máquinas virtuais do Linux
      url: /azure/virtual-machines/linux/ansible-install-configure
    - text: Executar guias estratégicos no Cloud Shell
      url: ansible-run-playbook-in-cloudshell.md
  - linkListType: tutorial
    links:
    - text: Configurar um inventário dinâmico
      url: ansible-manage-azure-dynamic-inventories.md
  - linkListType: download
    links:
    - text: Extensão do Visual Studio Code para Ansible
      url: https://marketplace.visualstudio.com/items?itemName=vscoss.vscode-ansible
- title: Gerenciar Máquinas Virtuais
  linkLists:
  - linkListType: quickstart
    links:
    - text: Configurar máquinas virtuais do Linux
      url: /azure/virtual-machines/linux/ansible-create-vm?toc=%2Fen-us%2Fazure%2Fansible%2Ftoc.json&bc=%2Fen-us%2Fazure%2Fbread%2Ftoc.json
    - text: Gerenciar máquinas virtuais do Linux
      url: /azure/virtual-machines/linux/ansible-manage-linux-vm?toc=%2Fen-us%2Fazure%2Fansible%2Ftoc.json&bc=%2Fen-us%2Fazure%2Fbread%2Ftoc.json
- title: Gerenciar os Conjuntos de Dimensionamento de Máquinas Virtuais
  linkLists:
  - linkListType: tutorial
    links:
    - text: Configurar os conjuntos de dimensionamento de máquinas virtuais
      url: ansible-create-configure-vmss.md
    - text: Implantar aplicativos nos conjuntos de dimensionamento de máquinas virtuais
      url: ansible-deploy-app-vmss.md
    - text: Dimensionar automaticamente conjuntos de dimensionamento de máquinas virtuais
      url: ansible-auto-scale-vmss.md
    - text: Atualizar imagem personalizada
      url: ansible-vmss-update-image.md
- title: Gerenciar Redes Virtuais
  linkLists:
  - linkListType: tutorial
    links:
    - text: Configurar o emparelhamento
      url: ansible-vnet-peering-configure.md
    - text: Configurar tabelas de rotas
      url: ansible-create-configure-route-table.md
- title: Gerenciar o AKS
  linkLists:
  - linkListType: tutorial
    links:
    - text: Configurar clusters do AKS
      url: ansible-create-configure-aks.md
    - text: Configurar a rede CNI do Azure
      url: ansible-aks-configure-cni-networking.md
    - text: Configurar a rede kubenet
      url: ansible-aks-configure-kubenet-networking.md
    - text: Configurar funções RBAC no cluster do AKS
      url: ansible-aks-configure-rbac.md
