### YamlMime:YamlDocument
ms.openlocfilehash: 5e2b31671a8f08bae1cba66e05d6ae72f960cf9e
ms.sourcegitcommit: d61faf71620a6a55dda014a665155f2a5dcd3fa2
ms.translationtype: HT
ms.contentlocale: pt-BR
ms.lasthandoff: 01/04/2019
ms.locfileid: "54050924"
documentType: LandingData
title: Ansible na documentação do Azure
metadata:
  title: Ansible na Documentação do Azure - Tutoriais, exemplos, referência e recursos
  description: Saiba como usar o Ansible para automatizar o provisionamento de nuvem, gerenciamento de configuração e implantações de aplicativo.
  ms.service: ansible
  keywords: ansible, azure, devops, tutoriais, exemplos, referência
  author: tomarchermsft
  manager: jeconnoc
  ms.author: tarcher
  ms.topic: landing-page
  ms.date: 08/27/2018
abstract:
  description: Use o <a href="https://www.ansible.com">Ansible</a> para automatizar o provisionamento de nuvem, gerenciamento de configurações e implantações do aplicativo.
sections:
- title: Guia de início rápido de 5 minutos
  items:
  - type: paragraph
    text: Instale o Ansible e use-o para criar e gerenciar máquinas virtuais Linux no Azure.
  - type: list
    style: icon48
    items:
    - image:
        src: /azure/media/index/azure_dev-9.svg
      text: Instalar o Ansible
      href: /azure/virtual-machines/linux/ansible-install-configure?toc=%2Fen-us%2Fazure%2Fansible%2Ftoc.json&bc=%2Fen-us%2Fazure%2Fbread%2Ftoc.json
    - image:
        src: /azure/media/index/VirtualMachine.svg
      text: Criar uma VM do Linux
      href: /azure/virtual-machines/linux/ansible-create-vm?toc=%2Fen-us%2Fazure%2Fansible%2Ftoc.json&bc=%2Fen-us%2Fazure%2Fbread%2Ftoc.json
    - image:
        src: /azure/media/index/VirtualMachine.svg
      text: Gerenciar uma VM do Linux
      href: /azure/virtual-machines/linux/ansible-manage-linux-vm?toc=%2Fen-us%2Fazure%2Fansible%2Ftoc.json&bc=%2Fen-us%2Fazure%2Fbread%2Ftoc.json
- title: Tutoriais Passo a Passo
  items:
  - type: paragraph
    text: Saiba como usar o Ansible para criar e gerenciar a infraestrutura de armazenamento, rede e computação do Azure.
  - type: list
    style: unordered
    items:
    - html: <a href="/azure/virtual-machines/linux/ansible-create-complete-vm?toc=%2Fen-us%2Fazure%2Fansible%2Ftoc.json&bc=%2Fen-us%2Fazure%2Fbread%2Ftoc.json">Crie uma máquina virtual do Linux, incluindo a rede virtual, endereço IP público e placa de interface de rede virtual.</a>
    - html: <a href="./ansible-run-playbook-in-cloudshell">Execute o Ansible com Bash no Azure Cloud Shell.</a>
    - html: <a href="./ansible-manage-azure-dynamic-inventories">Crie e gerencie um inventário dinâmico dos recursos do Azure.</a>
    - html: <a href="./ansible-create-configure-vmss">Criar e gerenciar conjuntos de dimensionamento de máquinas virtuais no Azure.</a>
    - html: <a href="./ansible-deploy-app-vmss">Implante aplicativos nos conjuntos de dimensionamento de máquinas virtuais no Azure.</a>
    - html: <a href="./ansible-create-configure-aks">Crie e gerencie clusters de Serviço de Kubernetes do Azure.</a>
    - html: <a href="./ansible-create-configure-application-gateway">Gerenciar tráfego da Web com um gateway de aplicativo do Azure.</a>
- title: Referência
  items:
  - type: list
    style: cards
    className: cardsD
    items:
    - title: Funções do manual
      html: <p><a href="https://galaxy.ansible.com/Azure/azure_preview_modules/">azure_preview_module</a></p>
    - title: Versões e recursos
      html: <p><a href="./ansible-matrix.md">Matriz de recursos para módulos e funções</a></p>
    - title: Ferramentas
      html: <p><a href="https://marketplace.visualstudio.com/items?itemName=vscoss.vscode-ansible">Extensão do Visual Studio Code para Ansible</a></p>
